# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_battery_voltage', models.FloatField(default=0.0)),
                ('time_in_float', models.FloatField(default=0.0)),
                ('max_current', models.FloatField(default=0.0)),
                ('accum_amp_hours', models.FloatField(default=0.0)),
                ('min_batt_volt_absorb_time', models.FloatField(default=0.0)),
                ('model', models.CharField(default='', max_length=15)),
                ('manufacturer', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amps', models.FloatField(default=0.0)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Battery')),
            ],
        ),
        migrations.CreateModel(
            name='CollectsFrom',
            fields=[
                ('date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amps', models.FloatField(default=0.0)),
                ('collected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CollectsFrom')),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField(default=0.0)),
                ('voltage', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('dc_power_rate', models.FloatField(default=0.0)),
                ('ampHours', models.FloatField(default=0.0)),
                ('kWProduction', models.FloatField(default=0.0)),
                ('model', models.CharField(default='', max_length=15)),
                ('manufacturer', models.CharField(default='', max_length=20)),
                ('fuel_type', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amps', models.FloatField(default=0.0)),
                ('amp_hours', models.FloatField(default=0.0)),
                ('peak_watts', models.FloatField(default=0.0)),
                ('solar_array_voltage', models.FloatField(default=0.0)),
                ('collected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CollectsFrom')),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_input', models.FloatField(default=0.0)),
                ('ac_output', models.FloatField(default=0.0)),
                ('model', models.CharField(default='', max_length=15)),
                ('manufacturer', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NodeController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('model', models.CharField(default='', max_length=15)),
                ('manufacturer', models.CharField(default='', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='NREL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('ghi', models.FloatField(default=0.0)),
                ('dni', models.FloatField(default=0.0)),
                ('dhi', models.FloatField(default=0.0)),
                ('air_temp', models.FloatField(default=0.0)),
                ('rel_humid', models.FloatField(default=0.0)),
                ('wind_speed', models.FloatField(default=0.0)),
                ('wind_dir', models.FloatField(default=0.0)),
                ('station_pressure', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='inverter',
            name='nc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NodeController'),
        ),
        migrations.AddField(
            model_name='idata',
            name='i_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Inverter'),
        ),
        migrations.AddField(
            model_name='generator',
            name='nc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NodeController'),
        ),
        migrations.AddField(
            model_name='gdata',
            name='g_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Generator'),
        ),
        migrations.AddField(
            model_name='bdata',
            name='collected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CollectsFrom'),
        ),
        migrations.AddField(
            model_name='battery',
            name='nc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NodeController'),
        ),
    ]
