# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 21:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batteries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('max_battery_voltage', models.FloatField(default=0.0)),
                ('time_in_float', models.FloatField(default=0.0)),
                ('max_current', models.FloatField(default=0.0)),
                ('accum_amp_hours', models.FloatField(default=0.0)),
                ('min_batt_volt_absorb_time', models.FloatField(default=0.0)),
                ('model', models.CharField(default='', max_length=15)),
                ('manufacturer', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amps', models.FloatField(default=0.0)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Batteries')),
            ],
        ),
        migrations.CreateModel(
            name='IData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amps', models.FloatField(default=0.0)),
                ('amp_hours', models.FloatField(default=0.0)),
                ('peak_watts', models.FloatField(default=0.0)),
                ('solar_array_voltage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Inverters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dc_input', models.FloatField(default=0.0)),
                ('ac_output', models.FloatField(default=0.0)),
                ('model', models.CharField(default='', max_length=15)),
                ('manufacturer', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='collectsfrom',
            name='id',
        ),
        migrations.AddField(
            model_name='collectsfrom',
            name='date',
            field=models.DateField(default=datetime.date.today, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nodecontrollers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inverters',
            name='nc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NodeControllers'),
        ),
        migrations.AddField(
            model_name='idata',
            name='collected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CollectsFrom'),
        ),
        migrations.AddField(
            model_name='idata',
            name='i_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Inverters'),
        ),
        migrations.AddField(
            model_name='bdata',
            name='collected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CollectsFrom'),
        ),
        migrations.AddField(
            model_name='batteries',
            name='nc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NodeControllers'),
        ),
    ]
