# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170330_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdata',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='gdata',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='idata',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='sdata',
            name='collected',
        ),
        migrations.DeleteModel(
            name='CollectsFrom',
        ),
    ]
