# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170220_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
