# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170203_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generators',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('frequency', models.FloatField(default=0.0)),
                ('voltage', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('dc_power_rate', models.FloatField(default=0.0)),
                ('ampHours', models.FloatField(default=0.0)),
                ('kWProduction', models.FloatField(default=0.0)),
                ('model', models.CharField(default='', max_length=15)),
                ('manufacturer', models.CharField(default='', max_length=20)),
                ('fuel_type', models.CharField(default='', max_length=15)),
                ('nc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.NodeControllers')),
            ],
        ),
    ]
