# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 22:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170319_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='dimension',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=None), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='battery',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
