# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_generators'),
    ]

    operations = [
        migrations.CreateModel(
            name='GData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amps', models.FloatField(default=0.0)),
                ('collected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CollectsFrom')),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Generators')),
            ],
        ),
    ]
