# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batteries',
            new_name='Battery',
        ),
        migrations.RenameModel(
            old_name='Generators',
            new_name='Generator',
        ),
        migrations.RenameModel(
            old_name='Inverters',
            new_name='Inverter',
        ),
        migrations.RenameModel(
            old_name='NodeControllers',
            new_name='NodeController',
        ),
    ]
